"""System/power action groups for DesktopTool."""

SYSTEM_ACTIONS = {
    "battery_status",
    "list_processes",
    "open_settings_page",
    "close_app",
    "launch_start_app",
    "system_power",
    "shutdown_schedule",
    "system_info",
    "clipboard_tools",
    "hardware_tools",
    "update_tools",
    "ui_tools",
    "automation_tools",
    "app_tools",
    "info_tools",
    "dev_tools",
    "shell_tools",
    "office_tools",
    "remote_tools",
    "search_tools",
    "performance_tools",
    "media_tools",
    "browser_deep_tools",
    "maintenance_tools",
    "driver_tools",
    "power_user_tools",
    "screenshot_tools",
    "text_tools",
    "api_tools",
}
